### ISSUE TITLE
[new rule] vue-scoped-css/v-deep-pseudo-style

### ISSUE THREAD

**Issue by baseballyama** [future-architect/eslint-plugin-vue-scoped-css#254]
~~I want to prevent using `v-deep` selector in my project but there is no such rule now.~~
~~And I think it should not be a general rule, so I thought that I will use `no-restricted-syntax` rule.~~
~~But there is no such rule now, so I created this issue.~~

~~If it should be declared as a general rule, maybe rule name is `vue-scoped-css/no-v-deep`?~~

It would be better if there is a rule that enforces to use `:deep()` or `::v-deep()`.

**Comment by ota-meshi** [comment]
Thanks for the rule suggestions. I think it would probably be good to add more than two rules.

- Rule for enforcing the style of `:deep()` <-> `::v-deep()`.
- Rule for enforcing the style of `:slotted()` <-> `::v-slotted()`.
- Rule for enforcing the style of `:global()` <-> `::v-global()`.

It would be even better if those rules had auto-fixer. I think a name like `vue-scoped-css/v-deep-style` is good because the rule just checks the style preference.

BTW, you can also use stylelint if you just want to check them.


https://stylelint.io/user-guide/rules/selector-pseudo-element-disallowed-list/

https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0BDABPeA3AtLGADgBRIBGAlGsADoB2aakANhAE7xqsxQDcdAvnTqoM+YmUo16jCC3adufWoNogANCADOAT1oAXFAA8E4TZvXgItAGYBLAOYmpDaiFYBXJjE2uOzhmiumjBeYHpsOATB7lAQOCEwALYw+ni2mihMLADu3DhM6Xq+aADargD0AHq45a4AunQMKvwg-EA

**Comment by baseballyama** [comment]
Oh sorry, maybe we have a misunderstanding.
I don't want to use both `:deep` and `::v-deep` because it has an impact on child components.
I mean a parent component should not know about a child component's DOM structure.

And I didn't know `selector-pseudo-element-disallowed-list` rule and now it works for me.
Thank you.

> I think it would probably be good to add more than two rules.

I agree that always we should use the same pseudo selector.

**Comment by ota-meshi** [comment]
Oh, I misunderstood that 😅 
For that usage, I think using stylelint's selector-pseudo-element-disallowed-list/selector-pseudo-class-disallowed-list is a good thing.
You can also use it to check `:global()` in svelte.

**Comment by baseballyama** [comment]
Oops now I updated this issue according to our discussion, but already you created a new issue.
So I close this now.
Thank you as always @ota-meshi !

**Comment by ota-meshi** [comment]
Oops, I closed it 😅. I will reopen a new issue.
